### ISSUE TITLE
App crashes when click on Playable Item from list

### ISSUE THREAD

**Issue by divyesh008** [Suplanus/Xamarin.Demo.Carplay#3]
I have implement CarPlay for my audio app using this sample. I have 2 issues.
1. List is showing different Title and SubTitle then what is actually provided 
2. When I click on list item in CarPlay simulator my MPPlayableContentDelegate's InitiatePlaybackOfContentItem() method gets call but then app crash.

**Crash message:** 
` Assertion failure in void _MPInitiatePlaybackCallback(MRMediaRemoteIndexPath, void *)_block_invoke(), /Library/Caches/com.apple.xbs/Sources/MediaPlayer_Sim/MobileMusicPlayer-4017.700.3/SDK/MPPlayableContentManager.m:722`

![Screenshot 2020-09-24 at 4 37 20 PM](https://user-images.githubusercontent.com/10617244/94137644-58f7e280-fe84-11ea-83c0-76dd2d0905a0.png)

**Comment by Suplanus** [comment]
The example is not finished yet. Sorry.
If I have time I will post the complete code.

**Comment by divyesh008** [comment]
@Suplanus Please can you post the complete code?? It would be really helpful

**Comment by Suplanus** [comment]
Sorry, there is no time for it...

**Comment by divyesh008** [comment]
At least you can update what should go inside InitiatePlaybackOfContentItem() method??

**Comment by Suplanus** [comment]
@divyesh008 I commited a working example

**Comment by divyesh008** [comment]
@Suplanus I have got the solution already, but thanks for update

**Comment by Suplanus** [comment]
Great. Perhaps you can enhance the demo. 

Have you catched the connecting event #1?
